# Bugs

* Replaced id for instance_id which caused _`$.id` could not be found in the datastructure_ on cluster plans. @itsouvalas